-- Insert Sample Products Data
-- Date: 2025-10-27
-- Note: Replace 'YOUR_USER_ID_HERE' with actual user UUID from your Supabase auth.users table

-- 1. Cinematic Portrait Presets
INSERT INTO products (
  "userId",
  title,
  description,
  price,
  "originalPrice",
  discount,
  image,
  "imagePairs",
  category,
  tags,
  compatibility,
  "fileFormat",
  "fileSize",
  "includesCount",
  features,
  specifications,
  warranty,
  rating,
  "reviewCount",
  downloads
) VALUES (
  'YOUR_USER_ID_HERE',
  'Cinematic Portrait Presets',
  'Transform your portraits with Hollywood-inspired color grading. Perfect for dramatic, moody photography with rich tones and film-like aesthetics. Includes 25 professional presets designed by award-winning photographers.',
  39.99,
  79.99,
  50,
  '/images/products/cinematic-portrait.jpg',
  '[{"before":"/images/before/cinematic-1.jpg","after":"/images/after/cinematic-1.jpg"},{"before":"/images/before/cinematic-2.jpg","after":"/images/after/cinematic-2.jpg"}]',
  'Presets',
  'portrait,cinematic,moody,film,color grading',
  'Lightroom Classic,Lightroom CC,Adobe Camera Raw',
  'XMP',
  '3.2 MB',
  25,
  'One-click installation,Professional color grading,Fully adjustable,Mobile & Desktop compatible,Video tutorials included',
  '{"adjustments":["Exposure & Contrast","Color Grading","Tone Curves","HSL Sliders"],"bestFor":["Portrait Photography","Fashion Editorial","Studio Work","Outdoor Portraits"],"difficulty":"Beginner"}',
  '{"duration":"Lifetime","coverage":"Free updates and support","terms":["30-day money-back guarantee","Instant download","Commercial license included"]}',
  4.9,
  234,
  3456
);

-- 2. Wedding Photography Bundle
INSERT INTO products (
  "userId",
  title,
  description,
  price,
  "originalPrice",
  discount,
  image,
  "imagePairs",
  category,
  tags,
  compatibility,
  "fileFormat",
  "fileSize",
  "includesCount",
  features,
  specifications,
  warranty,
  rating,
  "reviewCount",
  downloads
) VALUES (
  'YOUR_USER_ID_HERE',
  'Wedding Photography Bundle',
  'Complete wedding photography toolkit with 50 presets covering ceremony, reception, and portraits. Achieve consistent, romantic looks across all wedding shots. Trusted by professional wedding photographers worldwide.',
  59.99,
  119.99,
  50,
  '/images/products/wedding-bundle.jpg',
  '[{"before":"/images/before/wedding-1.jpg","after":"/images/after/wedding-1.jpg"},{"before":"/images/before/wedding-2.jpg","after":"/images/after/wedding-2.jpg"},{"before":"/images/before/wedding-3.jpg","after":"/images/after/wedding-3.jpg"}]',
  'Presets',
  'wedding,romance,soft,pastel,professional',
  'Lightroom Classic,Lightroom CC,Adobe Camera Raw,Lightroom Mobile',
  'XMP, DNG',
  '6.8 MB',
  50,
  'Ceremony presets,Reception presets,Portrait presets,Detail shot presets,Batch processing ready,Mobile presets included',
  '{"adjustments":["Skin Tone Enhancement","Soft Light Effects","White Balance Correction","Vignetting"],"bestFor":["Wedding Photography","Engagement Sessions","Couple Portraits","Bridal Photography"],"difficulty":"Beginner to Intermediate"}',
  '{"duration":"Lifetime","coverage":"Free updates forever","terms":["60-day money-back guarantee","Priority email support","Commercial use allowed"]}',
  5.0,
  567,
  8923
);

-- 3. Urban Street Photography Filters
INSERT INTO products (
  "userId",
  title,
  description,
  price,
  "originalPrice",
  discount,
  image,
  "imagePairs",
  category,
  tags,
  compatibility,
  "fileFormat",
  "fileSize",
  "includesCount",
  features,
  specifications,
  warranty,
  rating,
  "reviewCount",
  downloads
) VALUES (
  'YOUR_USER_ID_HERE',
  'Urban Street Photography Filters',
  'Gritty, edgy presets for urban photography. Enhance contrast, add grain, and create authentic street photography aesthetics. Perfect for documentary-style work and urban exploration.',
  29.99,
  49.99,
  40,
  '/images/products/urban-street.jpg',
  '[{"before":"/images/before/urban-1.jpg","after":"/images/after/urban-1.jpg"},{"before":"/images/before/urban-2.jpg","after":"/images/after/urban-2.jpg"}]',
  'Filters',
  'street,urban,gritty,documentary,black and white',
  'Lightroom Classic,Lightroom CC,Photoshop',
  'XMP, ATN',
  '2.1 MB',
  18,
  'High contrast looks,Film grain effects,B&W conversions,Color pop options,Quick editing workflow',
  '{"adjustments":["Contrast & Clarity","Grain & Texture","Selective Color","Shadows & Highlights"],"bestFor":["Street Photography","Urban Landscapes","Documentary Work","Travel Photography"],"difficulty":"Intermediate"}',
  '{"duration":"Lifetime","coverage":"Free updates","terms":["30-day money-back guarantee","Email support"]}',
  4.7,
  189,
  2341
);

-- 4. Golden Hour Landscape Pack
INSERT INTO products (
  "userId",
  title,
  description,
  price,
  "originalPrice",
  discount,
  image,
  "imagePairs",
  category,
  tags,
  compatibility,
  "fileFormat",
  "fileSize",
  "includesCount",
  features,
  specifications,
  warranty,
  rating,
  "reviewCount",
  downloads
) VALUES (
  'YOUR_USER_ID_HERE',
  'Golden Hour Landscape Pack',
  'Enhance those magical golden hour moments with warm, vibrant presets designed specifically for landscape photography. Bring out the best in sunrises, sunsets, and natural landscapes.',
  44.99,
  89.99,
  50,
  '/images/products/golden-hour.jpg',
  '[{"before":"/images/before/landscape-1.jpg","after":"/images/after/landscape-1.jpg"},{"before":"/images/before/landscape-2.jpg","after":"/images/after/landscape-2.jpg"},{"before":"/images/before/landscape-3.jpg","after":"/images/after/landscape-3.jpg"}]',
  'Presets',
  'landscape,golden hour,sunset,warm,nature',
  'Lightroom Classic,Lightroom CC,Adobe Camera Raw',
  'XMP',
  '4.5 MB',
  30,
  'Warm tone enhancement,Sky enhancement,Color vibrance boost,HDR effects,Panorama ready',
  '{"adjustments":["Temperature & Tint","Vibrance & Saturation","Graduated Filters","Clarity & Dehaze"],"bestFor":["Landscape Photography","Sunset Photography","Nature Photography","Travel Landscapes"],"difficulty":"Beginner"}',
  '{"duration":"Lifetime","coverage":"Free updates and tutorials","terms":["45-day money-back guarantee","Commercial license","Priority support"]}',
  4.8,
  412,
  5678
);

-- 5. Food Photography Essentials
INSERT INTO products (
  "userId",
  title,
  description,
  price,
  "originalPrice",
  discount,
  image,
  "imagePairs",
  category,
  tags,
  compatibility,
  "fileFormat",
  "fileSize",
  "includesCount",
  features,
  specifications,
  warranty,
  rating,
  "reviewCount",
  downloads
) VALUES (
  'YOUR_USER_ID_HERE',
  'Food Photography Essentials',
  'Make your food photos irresistible! Professional presets that enhance colors, textures, and appetite appeal. Perfect for restaurants, food bloggers, and culinary content creators.',
  34.99,
  69.99,
  50,
  '/images/products/food-photo.jpg',
  '[{"before":"/images/before/food-1.jpg","after":"/images/after/food-1.jpg"},{"before":"/images/before/food-2.jpg","after":"/images/after/food-2.jpg"}]',
  'Presets',
  'food,restaurant,culinary,appetizing,vibrant',
  'Lightroom Classic,Lightroom CC,Lightroom Mobile,Adobe Camera Raw',
  'XMP, DNG',
  '3.8 MB',
  22,
  'Color enhancement,Texture boost,Overhead shot presets,Close-up optimization,Instagram ready',
  '{"adjustments":["Color Saturation","Sharpness & Detail","White Balance","Vignette Effects"],"bestFor":["Food Photography","Restaurant Menus","Food Blogging","Social Media Content"],"difficulty":"Beginner"}',
  '{"duration":"Lifetime","coverage":"Free updates","terms":["30-day money-back guarantee","Commercial use allowed","Email support"]}',
  4.9,
  328,
  4521
);

-- 6. Newborn & Baby Soft Tones
INSERT INTO products (
  "userId",
  title,
  description,
  price,
  "originalPrice",
  discount,
  image,
  "imagePairs",
  category,
  tags,
  compatibility,
  "fileFormat",
  "fileSize",
  "includesCount",
  features,
  specifications,
  warranty,
  rating,
  "reviewCount",
  downloads
) VALUES (
  'YOUR_USER_ID_HERE',
  'Newborn & Baby Soft Tones',
  'Gentle, creamy presets designed specifically for newborn and baby photography. Achieve soft skin tones, dreamy atmospheres, and tender moments. Created by certified newborn photographers.',
  49.99,
  99.99,
  50,
  '/images/products/baby-soft.jpg',
  '[{"before":"/images/before/baby-1.jpg","after":"/images/after/baby-1.jpg"},{"before":"/images/before/baby-2.jpg","after":"/images/after/baby-2.jpg"}]',
  'Presets',
  'newborn,baby,soft,gentle,pastel',
  'Lightroom Classic,Lightroom CC,Adobe Camera Raw',
  'XMP',
  '2.9 MB',
  20,
  'Skin softening,Gentle color tones,Safe for sensitive editing,Pastel effects,Detail preservation',
  '{"adjustments":["Soft Focus","Skin Tone Correction","Gentle Lighting","Warmth Enhancement"],"bestFor":["Newborn Photography","Baby Portraits","Maternity Photos","Family Sessions"],"difficulty":"Beginner"}',
  '{"duration":"Lifetime","coverage":"Free updates and tutorials","terms":["60-day money-back guarantee","Priority support","Commercial license"]}',
  5.0,
  445,
  6234
);

-- 7. Adventure & Travel Collection
INSERT INTO products (
  "userId",
  title,
  description,
  price,
  "originalPrice",
  discount,
  image,
  "imagePairs",
  category,
  tags,
  compatibility,
  "fileFormat",
  "fileSize",
  "includesCount",
  features,
  specifications,
  warranty,
  rating,
  "reviewCount",
  downloads
) VALUES (
  'YOUR_USER_ID_HERE',
  'Adventure & Travel Collection',
  'Epic presets for travel and adventure photography. From mountain peaks to tropical beaches, enhance every destination with vibrant, inspiring looks. Includes presets for various lighting conditions.',
  54.99,
  109.99,
  50,
  '/images/products/adventure-travel.jpg',
  '[{"before":"/images/before/travel-1.jpg","after":"/images/after/travel-1.jpg"},{"before":"/images/before/travel-2.jpg","after":"/images/after/travel-2.jpg"},{"before":"/images/before/travel-3.jpg","after":"/images/after/travel-3.jpg"}]',
  'Presets',
  'travel,adventure,landscape,outdoor,wanderlust',
  'Lightroom Classic,Lightroom CC,Lightroom Mobile,Adobe Camera Raw',
  'XMP, DNG',
  '7.2 MB',
  45,
  'Landscape presets,Beach & ocean tones,Mountain & forest looks,Urban exploration,Action shot enhancement',
  '{"adjustments":["Dynamic Range","Color Vibrancy","Sky Enhancement","Adventure Tones"],"bestFor":["Travel Photography","Adventure Sports","Landscape","Outdoor Activities"],"difficulty":"Beginner to Intermediate"}',
  '{"duration":"Lifetime","coverage":"Free lifetime updates","terms":["45-day money-back guarantee","Video tutorials","Commercial use allowed"]}',
  4.8,
  523,
  7890
);

-- 8. Fashion Editorial Presets
INSERT INTO products (
  "userId",
  title,
  description,
  price,
  "originalPrice",
  discount,
  image,
  "imagePairs",
  category,
  tags,
  compatibility,
  "fileFormat",
  "fileSize",
  "includesCount",
  features,
  specifications,
  warranty,
  rating,
  "reviewCount",
  downloads
) VALUES (
  'YOUR_USER_ID_HERE',
  'Fashion Editorial Presets',
  'High-fashion magazine-quality presets for editorial photography. Clean, sophisticated looks with perfect skin tones and professional color grading used by top fashion photographers.',
  69.99,
  139.99,
  50,
  '/images/products/fashion-editorial.jpg',
  '[{"before":"/images/before/fashion-1.jpg","after":"/images/after/fashion-1.jpg"},{"before":"/images/before/fashion-2.jpg","after":"/images/after/fashion-2.jpg"}]',
  'Presets',
  'fashion,editorial,magazine,high-end,professional',
  'Lightroom Classic,Lightroom CC,Adobe Camera Raw,Photoshop',
  'XMP, ATN',
  '5.4 MB',
  35,
  'Editorial color grading,Skin retouching,High fashion looks,Studio lighting enhancement,Runway ready',
  '{"adjustments":["Professional Color Grading","Skin Tone Perfection","Contrast Control","Magazine Quality"],"bestFor":["Fashion Photography","Editorial Shoots","Beauty Photography","Modeling Portfolios"],"difficulty":"Intermediate to Advanced"}',
  '{"duration":"Lifetime","coverage":"Premium support & updates","terms":["60-day money-back guarantee","Priority email support","Full commercial license","Video masterclass included"]}',
  4.9,
  298,
  4123
);

-- 9. Black & White Master Collection
INSERT INTO products (
  "userId",
  title,
  description,
  price,
  "originalPrice",
  discount,
  image,
  "imagePairs",
  category,
  tags,
  compatibility,
  "fileFormat",
  "fileSize",
  "includesCount",
  features,
  specifications,
  warranty,
  rating,
  "reviewCount",
  downloads
) VALUES (
  'YOUR_USER_ID_HERE',
  'Black & White Master Collection',
  'Timeless black and white conversions inspired by legendary film photographers. From high-contrast drama to subtle fine-art tones. 40 carefully crafted monochrome presets for any genre.',
  44.99,
  89.99,
  50,
  '/images/products/bw-master.jpg',
  '[{"before":"/images/before/bw-1.jpg","after":"/images/after/bw-1.jpg"},{"before":"/images/before/bw-2.jpg","after":"/images/after/bw-2.jpg"}]',
  'Filters',
  'black and white,monochrome,classic,timeless,film',
  'Lightroom Classic,Lightroom CC,Adobe Camera Raw,Photoshop',
  'XMP, ATN',
  '4.1 MB',
  40,
  'Classic film looks,High contrast options,Fine art tones,Split toning,Grain effects',
  '{"adjustments":["B&W Conversion","Contrast & Tonality","Film Grain","Tonal Separation"],"bestFor":["Fine Art Photography","Portrait Photography","Street Photography","Architectural Photography"],"difficulty":"Intermediate"}',
  '{"duration":"Lifetime","coverage":"Free updates forever","terms":["45-day money-back guarantee","Tutorial videos","Commercial license"]}',
  4.8,
  367,
  5012
);

-- 10. Mobile Lifestyle Presets
INSERT INTO products (
  "userId",
  title,
  description,
  price,
  "originalPrice",
  discount,
  image,
  "imagePairs",
  category,
  tags,
  compatibility,
  "fileFormat",
  "fileSize",
  "includesCount",
  features,
  specifications,
  warranty,
  rating,
  "reviewCount",
  downloads
) VALUES (
  'YOUR_USER_ID_HERE',
  'Mobile Lifestyle Presets',
  'Instagram-ready presets optimized for mobile photography. Perfect for influencers, bloggers, and content creators. Achieve consistent, trendy aesthetics with one tap on your phone.',
  24.99,
  49.99,
  50,
  '/images/products/mobile-lifestyle.jpg',
  '[{"before":"/images/before/mobile-1.jpg","after":"/images/after/mobile-1.jpg"},{"before":"/images/before/mobile-2.jpg","after":"/images/after/mobile-2.jpg"}]',
  'Presets',
  'mobile,instagram,lifestyle,social media,influencer',
  'Lightroom Mobile,Lightroom CC',
  'DNG',
  '1.8 MB',
  28,
  'One-tap editing,Instagram optimized,Consistent feed aesthetic,Mobile-first design,Story templates',
  '{"adjustments":["Social Media Ready","Bright & Airy","Moody Vibes","Trendy Colors"],"bestFor":["Instagram","Social Media","Lifestyle Blogging","Mobile Photography"],"difficulty":"Beginner"}',
  '{"duration":"Lifetime","coverage":"Free updates","terms":["30-day money-back guarantee","Installation guide","Personal & commercial use"]}',
  4.7,
  892,
  12345
);

-- Note: After inserting, you should:
-- 1. Replace 'YOUR_USER_ID_HERE' with actual UUID from auth.users
-- 2. Upload actual product images to your storage
-- 3. Update image paths to match your storage URLs
